// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'v_bhxh';

  static bool isFromModules = false;

  static String get ASSETS_FONTS_NUNITOSANS_BOLD_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/NunitoSans-Bold.ttf';

  static String get ASSETS_FONTS_NUNITOSANS_EXTRABOLD_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/NunitoSans-ExtraBold.ttf';

  static String get ASSETS_FONTS_NUNITOSANS_REGULAR_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/NunitoSans-Regular.ttf';

  static String get ASSETS_FONTS_NUNITOSANS_SEMIBOLD_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/NunitoSans-SemiBold.ttf';

  static String get ASSETS_FONTS_ROBOTO_BOLD_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/Roboto-Bold.ttf';

  static String get ASSETS_FONTS_ROBOTO_MEDIUM_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/Roboto-Medium.ttf';

  static String get ASSETS_FONTS_ROBOTO_REGULAR_TTF =>
      '${isFromModules ? "packages/$package/" : ""}assets/fonts/Roboto-Regular.ttf';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_DECLARATION_SVG.preview}
  static String get ASSETS_ICONS_HOME_DECLARATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/declaration.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HISTORY_SVG.preview}
  static String get ASSETS_ICONS_HOME_HISTORY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HOME_SVG.preview}
  static String get ASSETS_ICONS_HOME_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/home.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_GUIDE_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_GUIDE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_guide.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_HOME_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_home.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_NOTIFICATION_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_notification.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_PROFILE_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_REGISTER_SERVICE_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_REGISTER_SERVICE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_register_service.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_STATIS_SVG.preview}
  static String get ASSETS_ICONS_HOME_IC_STATIS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/ic_statis.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_LOOKUP_C12_SVG.preview}
  static String get ASSETS_ICONS_HOME_LOOKUP_C12_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/lookup_c12.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_UNIT_INFO_SVG.preview}
  static String get ASSETS_ICONS_HOME_UNIT_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/unit_info.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_IMAGE_SVG.preview}
  static String get ASSETS_ICONS_IC_ADD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_add_image.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_DOWN_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_DOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_down.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LARGE_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_LARGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_large.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LEFT_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_left.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_RIGHT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_right.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_UP_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_UP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_up.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CALENDAR_SVG.preview}
  static String get ASSETS_ICONS_IC_CALENDAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_calendar.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CCCD_SVG.preview}
  static String get ASSETS_ICONS_IC_CCCD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_cccd.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLEAR_SVG.preview}
  static String get ASSETS_ICONS_IC_CLEAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_clear.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_SVG.preview}
  static String get ASSETS_ICONS_IC_DELETE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_delete.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DOCUMENT_SVG.preview}
  static String get ASSETS_ICONS_IC_DOCUMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_document.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DRAG_HANDLE_SVG.preview}
  static String get ASSETS_ICONS_IC_DRAG_HANDLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_drag_handle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DROPDOWN_SVG.preview}
  static String get ASSETS_ICONS_IC_DROPDOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_dropdown.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_SVG.preview}
  static String get ASSETS_ICONS_IC_EDIT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_edit.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EYE_SVG.preview}
  static String get ASSETS_ICONS_IC_EYE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_eye.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FILTER_SVG.preview}
  static String get ASSETS_ICONS_IC_FILTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_filter.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_GROUP_SVG.preview}
  static String get ASSETS_ICONS_IC_GROUP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_group.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_HUGE_SVG.preview}
  static String get ASSETS_ICONS_IC_HUGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_huge.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_IMPORT_SVG.preview}
  static String get ASSETS_ICONS_IC_IMPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_import.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOOKUP_MY_SIGN_SVG.preview}
  static String get ASSETS_ICONS_IC_LOOKUP_MY_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_lookup_my_sign.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NATION_SVG.preview}
  static String get ASSETS_ICONS_IC_NATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_nation.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOT_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOT_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_not_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_DECLARE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_DECLARE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_declare.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_DELETE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_DELETE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_delete.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_SETTING_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_SETTING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_setting.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_UNIT_INFO_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_UNIT_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_unit_info.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSON_SVG.preview}
  static String get ASSETS_ICONS_IC_PERSON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_person.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSONAL_SVG.preview}
  static String get ASSETS_ICONS_IC_PERSONAL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_personal.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROCEDURE_SVG.preview}
  static String get ASSETS_ICONS_IC_PROCEDURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_procedure.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  static String get ASSETS_ICONS_IC_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REGISTER_SVG.preview}
  static String get ASSETS_ICONS_IC_REGISTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_register.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMOVE_SVG.preview}
  static String get ASSETS_ICONS_IC_REMOVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_remove.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SCAN_NFC_SVG.preview}
  static String get ASSETS_ICONS_IC_SCAN_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_scan_nfc.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SCAN_NFC_GET_INFO_SVG.preview}
  static String get ASSETS_ICONS_IC_SCAN_NFC_GET_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_scan_nfc_get_info.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_SVG.preview}
  static String get ASSETS_ICONS_IC_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_search.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_START_DAY_SVG.preview}
  static String get ASSETS_ICONS_IC_START_DAY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_start_day.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_UP_FILE_SVG.preview}
  static String get ASSETS_ICONS_IC_UP_FILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_up_file.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SVG.preview}
  static String get ASSETS_ICONS_IC_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_user.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_BIRTHDAY_SVG.preview}
  static String get ASSETS_ICONS_ICON_BIRTHDAY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_birthday.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CARD_INFO_SVG.preview}
  static String get ASSETS_ICONS_ICON_CARD_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_card_info.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_GENDER_SVG.preview}
  static String get ASSETS_ICONS_ICON_GENDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_gender.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOURGLASS_SVG.preview}
  static String get ASSETS_ICONS_ICON_HOURGLASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_hourglass.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LIST_NULL_SVG.preview}
  static String get ASSETS_ICONS_ICON_LIST_NULL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_list_null.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_MAP_SVG.preview}
  static String get ASSETS_ICONS_ICON_MAP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_map.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NATIONALITY_SVG.preview}
  static String get ASSETS_ICONS_ICON_NATIONALITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_nationality.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_SVG.preview}
  static String get ASSETS_ICONS_ICON_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_nfc.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_HOME_TOWN_SVG.preview}
  static String get ASSETS_ICONS_ICON_NFC_HOME_TOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_nfc_home_town.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  static String get ASSETS_ICONS_ICON_NFC_IDENTIFYING_SIGNS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_nfc_identifying_signs.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_fail.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_notification.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_success.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_warning.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_USER_NAME_CARD_SVG.preview}
  static String get ASSETS_ICONS_ICON_USER_NAME_CARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_user_name_card.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG.preview}
  static String get ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_check_failure.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG.preview}
  static String get ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_check_success.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IPHONE_JPG.preview}
  static String get ASSETS_IMAGES_IPHONE_JPG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/iphone.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_LOGO_VIETTEL_SVG.preview}
  static String get ASSETS_IMAGES_LOGO_VIETTEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/logo_viettel.svg';

  static String get ASSETS_LOCALES_EN_US_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/en_US.json';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';
}

final List<String> assetsArray = <String>[
  Assets.ASSETS_FONTS_NUNITOSANS_BOLD_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_EXTRABOLD_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_REGULAR_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_SEMIBOLD_TTF,
  Assets.ASSETS_FONTS_ROBOTO_BOLD_TTF,
  Assets.ASSETS_FONTS_ROBOTO_MEDIUM_TTF,
  Assets.ASSETS_FONTS_ROBOTO_REGULAR_TTF,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_DECLARATION_SVG.preview}
  Assets.ASSETS_ICONS_HOME_DECLARATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_HOME_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HOME_SVG.preview}
  Assets.ASSETS_ICONS_HOME_HOME_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_GUIDE_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_GUIDE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_HOME_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_HOME_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_NOTIFICATION_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_REGISTER_SERVICE_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_REGISTER_SERVICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_IC_STATIS_SVG.preview}
  Assets.ASSETS_ICONS_HOME_IC_STATIS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_LOOKUP_C12_SVG.preview}
  Assets.ASSETS_ICONS_HOME_LOOKUP_C12_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_UNIT_INFO_SVG.preview}
  Assets.ASSETS_ICONS_HOME_UNIT_INFO_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_IMAGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ADD_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_DOWN_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_DOWN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LARGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_LARGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LEFT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_RIGHT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_UP_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_UP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CALENDAR_SVG.preview}
  Assets.ASSETS_ICONS_IC_CALENDAR_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CCCD_SVG.preview}
  Assets.ASSETS_ICONS_IC_CCCD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLEAR_SVG.preview}
  Assets.ASSETS_ICONS_IC_CLEAR_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_SVG.preview}
  Assets.ASSETS_ICONS_IC_DELETE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DOCUMENT_SVG.preview}
  Assets.ASSETS_ICONS_IC_DOCUMENT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DRAG_HANDLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_DRAG_HANDLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DROPDOWN_SVG.preview}
  Assets.ASSETS_ICONS_IC_DROPDOWN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_SVG.preview}
  Assets.ASSETS_ICONS_IC_EDIT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EYE_SVG.preview}
  Assets.ASSETS_ICONS_IC_EYE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FILTER_SVG.preview}
  Assets.ASSETS_ICONS_IC_FILTER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_GROUP_SVG.preview}
  Assets.ASSETS_ICONS_IC_GROUP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_HUGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_HUGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_IMPORT_SVG.preview}
  Assets.ASSETS_ICONS_IC_IMPORT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOOKUP_MY_SIGN_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOOKUP_MY_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NATION_SVG.preview}
  Assets.ASSETS_ICONS_IC_NATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOT_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOT_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_DECLARE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_DECLARE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_DELETE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_DELETE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_SETTING_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_SETTING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_UNIT_INFO_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_UNIT_INFO_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSON_SVG.preview}
  Assets.ASSETS_ICONS_IC_PERSON_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSONAL_SVG.preview}
  Assets.ASSETS_ICONS_IC_PERSONAL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROCEDURE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROCEDURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REGISTER_SVG.preview}
  Assets.ASSETS_ICONS_IC_REGISTER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMOVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_REMOVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SCAN_NFC_SVG.preview}
  Assets.ASSETS_ICONS_IC_SCAN_NFC_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SCAN_NFC_GET_INFO_SVG.preview}
  Assets.ASSETS_ICONS_IC_SCAN_NFC_GET_INFO_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_START_DAY_SVG.preview}
  Assets.ASSETS_ICONS_IC_START_DAY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_UP_FILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_UP_FILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SVG.preview}
  Assets.ASSETS_ICONS_IC_USER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_BIRTHDAY_SVG.preview}
  Assets.ASSETS_ICONS_ICON_BIRTHDAY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CARD_INFO_SVG.preview}
  Assets.ASSETS_ICONS_ICON_CARD_INFO_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_GENDER_SVG.preview}
  Assets.ASSETS_ICONS_ICON_GENDER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOURGLASS_SVG.preview}
  Assets.ASSETS_ICONS_ICON_HOURGLASS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LIST_NULL_SVG.preview}
  Assets.ASSETS_ICONS_ICON_LIST_NULL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_MAP_SVG.preview}
  Assets.ASSETS_ICONS_ICON_MAP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NATIONALITY_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NATIONALITY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NFC_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_HOME_TOWN_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NFC_HOME_TOWN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NFC_IDENTIFYING_SIGNS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_USER_NAME_CARD_SVG.preview}
  Assets.ASSETS_ICONS_ICON_USER_NAME_CARD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG.preview}
  Assets.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG.preview}
  Assets.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IPHONE_JPG.preview}
  Assets.ASSETS_IMAGES_IPHONE_JPG,

  /// {@macro assets_generator.ASSETS_IMAGES_LOGO_VIETTEL_SVG.preview}
  Assets.ASSETS_IMAGES_LOGO_VIETTEL_SVG,
  Assets.ASSETS_LOCALES_EN_US_JSON,
  Assets.ASSETS_LOCALES_VI_VN_JSON,
];
