// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'v_bhxh';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_ICONS_HOME_FILE_DECLARATION_SVG.preview}
  static String get ASSETS_ICONS_HOME_FILE_DECLARATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/file_declaration.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HOME_SVG.preview}
  static String get ASSETS_ICONS_HOME_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/home.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_LOOKUP_C12_SVG.preview}
  static String get ASSETS_ICONS_HOME_LOOKUP_C12_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/lookup_c12.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_REGISTER_TRANSACTION_SVG.preview}
  static String get ASSETS_ICONS_HOME_REGISTER_TRANSACTION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/register_transaction.svg';

  /// {@macro assets_generator.ASSETS_ICONS_HOME_TRANSACTION_HISTORY_SVG.preview}
  static String get ASSETS_ICONS_HOME_TRANSACTION_HISTORY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/home/transaction_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_IMAGE_SVG.preview}
  static String get ASSETS_ICONS_IC_ADD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_add_image.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_DOWN_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_DOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_down.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LARGE_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_LARGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_large.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LEFT_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_left.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_RIGHT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_right.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_UP_SVG.preview}
  static String get ASSETS_ICONS_IC_ARROW_UP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_arrow_up.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CALENDER_SVG.preview}
  static String get ASSETS_ICONS_IC_CALENDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_calender.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DOCUMENT_SVG.preview}
  static String get ASSETS_ICONS_IC_DOCUMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_document.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DRAG_HANDLE_SVG.preview}
  static String get ASSETS_ICONS_IC_DRAG_HANDLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_drag_handle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DROPDOWN_SVG.preview}
  static String get ASSETS_ICONS_IC_DROPDOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_dropdown.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_SVG.preview}
  static String get ASSETS_ICONS_IC_EDIT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_edit.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FILTER_SVG.preview}
  static String get ASSETS_ICONS_IC_FILTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_filter.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_GROUP_SVG.preview}
  static String get ASSETS_ICONS_IC_GROUP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_group.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_HUGE_SVG.preview}
  static String get ASSETS_ICONS_IC_HUGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_huge.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_IMPORT_SVG.preview}
  static String get ASSETS_ICONS_IC_IMPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_import.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOT_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOT_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_not_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  static String get ASSETS_ICONS_IC_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REGISTER_SVG.preview}
  static String get ASSETS_ICONS_IC_REGISTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_register.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMOVE_SVG.preview}
  static String get ASSETS_ICONS_IC_REMOVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_remove.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_SVG.preview}
  static String get ASSETS_ICONS_IC_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_search.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SVG.preview}
  static String get ASSETS_ICONS_IC_USER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_user.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOURGLASS_SVG.preview}
  static String get ASSETS_ICONS_ICON_HOURGLASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_hourglass.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_fail.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_notification.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_success.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_warning.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG.preview}
  static String get ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_check_failure.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG.preview}
  static String get ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_check_success.svg';

  static String get ASSETS_LOCALES_EN_US_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/en_US.json';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.ASSETS_ICONS_HOME_FILE_DECLARATION_SVG.preview}
  Assets.ASSETS_ICONS_HOME_FILE_DECLARATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_HOME_SVG.preview}
  Assets.ASSETS_ICONS_HOME_HOME_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_LOOKUP_C12_SVG.preview}
  Assets.ASSETS_ICONS_HOME_LOOKUP_C12_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_REGISTER_TRANSACTION_SVG.preview}
  Assets.ASSETS_ICONS_HOME_REGISTER_TRANSACTION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_HOME_TRANSACTION_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_HOME_TRANSACTION_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_IMAGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ADD_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_DOWN_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_DOWN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LARGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_LARGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_LEFT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_RIGHT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_UP_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_UP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CALENDER_SVG.preview}
  Assets.ASSETS_ICONS_IC_CALENDER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DOCUMENT_SVG.preview}
  Assets.ASSETS_ICONS_IC_DOCUMENT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DRAG_HANDLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_DRAG_HANDLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DROPDOWN_SVG.preview}
  Assets.ASSETS_ICONS_IC_DROPDOWN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_SVG.preview}
  Assets.ASSETS_ICONS_IC_EDIT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FILTER_SVG.preview}
  Assets.ASSETS_ICONS_IC_FILTER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_GROUP_SVG.preview}
  Assets.ASSETS_ICONS_IC_GROUP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_HUGE_SVG.preview}
  Assets.ASSETS_ICONS_IC_HUGE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_IMPORT_SVG.preview}
  Assets.ASSETS_ICONS_IC_IMPORT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOT_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOT_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REGISTER_SVG.preview}
  Assets.ASSETS_ICONS_IC_REGISTER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMOVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_REMOVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SVG.preview}
  Assets.ASSETS_ICONS_IC_USER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOURGLASS_SVG.preview}
  Assets.ASSETS_ICONS_ICON_HOURGLASS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_FAIL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG.preview}
  Assets.ASSETS_IMAGES_IMG_CHECK_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG.preview}
  Assets.ASSETS_IMAGES_IMG_CHECK_SUCCESS_SVG,
  Assets.ASSETS_LOCALES_EN_US_JSON,
  Assets.ASSETS_LOCALES_VI_VN_JSON,
];
